sudo: false
language: ruby
rvm:
  - 2.3.0
services:
  - docker
before_install:
  - gem install bundler -v 1.13.6
  - cd $TRAVIS_BUILD_DIR/docker/redis_cluster && docker build -t redis-cluster .
before_script:
  - docker run -d -p 30001:30001 -p 30002:30002 -p 30003:30003 -p 30004:30004 -p 30005:30005 -p 30006:30006 -t redis-cluster
  - sleep 2
