sudo: false
language: ruby
rvm:
  - 2.3.0
before_install:
  - gem install bundler -v 1.13.6
  - git clone https://github.com/antirez/redis $TRAVIS_BUILD_DIR/redis && cd $TRAVIS_BUILD_DIR/redis && make
before_script:
  - cd $TRAVIS_BUILD_DIR/redis/utils/create-cluster && ./create-cluster start && yes yes | ./create-cluster create
  - cd $TRAVIS_BUILD_DIR
after_script:
  - cd $TRAVIS_BUILD_DIR/redis/utils/create-cluster && ./create-cluster stop && ./create-cluster clean
